# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS-Template-UIKIT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for IOS-Template-UIKIT

  target 'IOS-Template-UIKITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS-Template-UIKITUITests' do
    # Pods for testing
  end

end
